### ISSUE TITLE
FB is at it again; photo posts nonfunctional on the timeline

### ISSUE THREAD

**Issue by Orudeon** [ThinkBIG-Company/instantgram-light#4] opened 2023-08-01 18:11 UTC
Seems like videos are functional, individual posts on someone's profile work, and stories remain functional, though.

Firefox 115.0.3, windows 10 64-bit, west coast united states. Thanks for looking at this!

**Comment by ThinkBIG-Company** [comment] 2023-08-02 18:10
Please retry, i cannot reproduce the bug.

**Comment by Orudeon** [comment] 2023-08-02 20:17
[This is what happens to every photo on the timeline](https://i.imgur.com/p4OKXj4.png), it's weird that the problem can't be reproduced.

**Comment by ThinkBIG-Company** [comment] 2023-08-06 19:37
Ok can confirm it have changed the ip to usa and now i can see the bug...

**Comment by ThinkBIG-Company** [comment] 2023-08-08 07:28
I can only see the error when i am logged out and i am on this address https://instagram.com/
Can you please write here the error you see in the console, can be opened with F12 on your keyboard.

**Comment by Orudeon** [comment] 2023-08-08 18:27
Here's a pastebin of the error

https://pastebin.com/WhrfnBad

[Here's an image of a short version, in case that's more useful](https://i.imgur.com/dAbfsEG.png)

**Comment by ThinkBIG-Company** [comment] 2023-08-16 19:20
Hello,
it turns out that instagram is trying everything possible to fight piracy.
So far only pictures are affected, videos not yet.
Think that's only a matter of time until videos will soon no longer be recognized.
Maybe instagram also became aware of this repository and studied the code to prevent piracy, because I was always one step ahead.

I'm really sorry I don't have a fix, maybe soon I'll have a divine inspiration like the last times and I'll be better than Instagram again.

Thank you so much for all your support it has helped me so much and done me so much good.

Translated with www.DeepL.com/Translator (free version)

**Comment by Orudeon** [comment] 2023-08-16 20:32
You've done so much to try to stay ahead of them; I only have thanks for you for working so hard to stay ahead of them.

**Comment by ThinkBIG-Company** [comment] 2023-10-27 19:10
New update released should be fixed.

**Closed by ThinkBIG-Company** 2023-10-27 19:10 UTC
Labels: bug
